name: Test defaults

on:
  pull_request:
    paths:
      - action.yaml
      - recipes/defaults/construct.yaml
      - .github/workflows/test-defaults.yaml
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build-installer:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
    name: Miniconda, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683       # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@505e6394dae86d6a5c7fbb6e3fb8938e3e863830  # v3.1.1
        with:
          activate-environment: ''
          run-post: false

      - name: Create installer
        id: create-installer
        uses: ./
        with:
          environment-yaml-string: |
            channels:
              - defaults
            dependencies:
              - constructor
              ${{ matrix.os == 'windows' && '- nsis=*=*_log_*' || '' }}
            variables:
              ${{ matrix.os == 'macos' && 'CONDA_OVERRIDE_OSX: 12.0' || '' }}
              EXT: ${{ matrix.os == 'windows' && 'exe' || 'sh' }}
              NSIS_USING_LOG_BUILD: 1
          conda-root: ${{ env.CONDA }}
          input-directory: recipes/defaults

      - name: Upload installer to Github artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02       # v4.6.2
        with:
          path: ${{ steps.create-installer.outputs.artifacts-directory }}/*
          name: defaults-test-${{ matrix.os }}
          retention-days: 5

      - name: Determine installer file name
        id: installer-file
        run: |
          SHAFILE=$(find "${{ steps.create-installer.outputs.artifacts-directory }}" -name "*.sha256" | head -n 1)
          echo "installer-file=${SHAFILE/\.sha256/}" >> ${GITHUB_OUTPUT}
        shell: bash

      - name: Verify hashes
        env:
          ARTIFACTS_DIRECTORY: ${{ steps.create-installer.outputs.artifacts-directory }}
          INSTALLER_FILE: ${{ steps.installer-file.outputs.installer-file }}
        run: |
          UNAME=$(uname)
          [[ "${UNAME}" == MINGW* ]] && ARTIFACTS_DIRECTORY=$(cygpath "${ARTIFACTS_DIRECTORY}")
          [[ "${UNAME}" == "Darwin" ]] && SHACMD="shasum -a 256" || SHACMD=sha256sum
          cd ${ARTIFACTS_DIRECTORY}
          ${SHACMD} -c "${INSTALLER_FILE}.sha256"
        shell: bash

      - name: Run installer
        uses: conda-incubator/setup-miniconda@505e6394dae86d6a5c7fbb6e3fb8938e3e863830       # v3.1.1
        with:
          activate-environment: ''
          installation-dir: ${{ runner.temp }}/installer_test
          installer-url: file://${{ steps.installer-file.outputs.installer-file }}

      - name: Test installer
        env:
          INSTALL_DIR: ${{ runner.temp }}/installer_test
        run: |
          if [[ $(uname) == MINGW* ]]; then
              CONDA=$(cygpath "${CONDA}")
          fi
          . ${CONDA}/etc/profile.d/conda.sh
          conda activate
          conda info --json | python -c "import json, os, sys; from pathlib import Path; info = json.loads(sys.stdin.read()); assert Path(os.environ.get('INSTALL_DIR', '')).samefile(info['root_prefix'])"
          if [[ $(uname) == MINGW* ]]; then
              test -f "${CONDA}/install.log"
          fi
        shell: bash
